version: "3"

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend/
    #    command: ["/bin/bash", "-c", "python app/main.py"]
    command: [ "tail", "-f", "/dev/null" ]
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000

  db:
    image: postgres:12.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./backend/.env
    ports:
      - 5432:5432

volumes:
  postgres_data: